[project]
name = "toyama-2g"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "YoichiUsui", email = "koi.usui@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pyqt6>=6.7,<7",
    "pyserial==3.5",
]

[project.scripts]
toyama-2g = "toyama_2g:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
